### ISSUE TITLE
Refactor register handler

### ISSUE THREAD

**Issue by Pe4kin1703** [Braun-Alex/pet-adoption#4]
Сделай пожалуйста рефактор RegisterRequestHandler. 
Согласно первому принципу SOLID (единой ответственности) одна функция должна решать 1 задачу.
Учитывая это, хендлер, который обрабатывает регистрацию пользователя, не должно интересовать хешируем ли мы пароль, добавляем ли мы salt к этому паролю при хешировании. Так же его не должно интересовать куда мы сохраняем Юзера, будь то база данных или файловая система.

В связи с этим нам стоит подумать про дополнительные сущности, которые нужны помимо хендлеров.

**Comment by Braun-Alex** [comment]
Зроблено.
